.TH MEH-DO "1" "March 2018" "1" "MEH-DO"
.SH NAME
meh-do \- Executes commands as root
.SH SYNOPSIS
.B meh-do
[command]
.SH DESCRIPTION
.B meh-do
runs a single command as root, much like sudo(1) but without any checks. This
command should NOT be used.
.SH "SEE ALSO"
.sp
\fBsudo(1)\fP
.SH AUTHOR
Written by Kyle Laker
.SH COPYRIGHT
Copyright \(co 2018 Kyle Laker

